# Arrays vs. Lists

In [1]:
import numpy as np

In [2]:
L = [1, 2, 3]

In [3]:
A = np.array([1, 2, 3])

In [4]:
for i  in L:
    print(i)

1
2
3


In [5]:
for i in A:
    print(i)

1
2
3


In [6]:
L.append(4)

L

[1, 2, 3, 4]

In [10]:
try:
    A.append(4)
except AttributeError as err:
    print('Array has fixed size', '\n', err)

Array has fixed size 
 'numpy.ndarray' object has no attribute 'append'


In [12]:
L + [5]

[1, 2, 3, 4, 5]

In [16]:
A + np.array([4]) 
# array([5, 6, 7])
# Calls roadcasting. Sum of different vector sizes is kind ilegal in math... But can be done with Numpy

array([5, 6, 7])

In [17]:
A + np.array([4, 5, 6])

array([5, 7, 9])

In [19]:
try:
    A + np.array([4, 5])
except ValueError as err:
    print('Can\'t add vector with different sizes', '\n', err)

Can't add vector with different sizes 
 operands could not be broadcast together with shapes (3,) (2,) 


In [21]:
2 * L

[1, 2, 3, 4, 1, 2, 3, 4]

In [20]:
2 * A

array([2, 4, 6])

In [22]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [23]:
A + A

array([2, 4, 6])

In [24]:
L2 = []
for i in L:
    L2.append(i + 3)
    
L2

[4, 5, 6, 7]

In [25]:
[i + 3 for i in L]

[4, 5, 6, 7]

In [27]:
try:
    L**2
except TypeError as err:
    print(err)

unsupported operand type(s) for ** or pow(): 'list' and 'int'


In [29]:
L2 = []

for i in L:
    L2.append(i**2)
    
L2

[1, 4, 9, 16]

In [30]:
A**2

array([1, 4, 9])

In [31]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [32]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [33]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [34]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])