# Solving Linear Systems

In [1]:
import numpy as np
from numpy import linalg as la

The admission fee at small fair is $1.5 for children and $4 for adults. On a certain day, 2200 people enter the fair, and $5050 is collected. How many children and how many adults attended?

$$
x_1 + x_2 = 2200
$$

$$
1.5x_1 + 4x_2 = 5050
$$

$$
x = 
\begin{pmatrix}
    x_1 \\ 
    x_2
\end{pmatrix}
,
A = 
\begin{pmatrix}
    1 & 1 \\ 
    1.5 & 4
\end{pmatrix}
,
b = 
\begin{pmatrix}
    2200 \\ 
    5050
\end{pmatrix}
$$

$$
A_x = b <=> x = A^{-1}b
$$

In [3]:
A = np.array([[1, 1], [1.5, 4]])

A

array([[1. , 1. ],
       [1.5, 4. ]])

In [5]:
b = np.array([2200, 5050])

b

array([2200, 5050])

In [6]:
la.solve(A, b)

array([1500.,  700.])

In [7]:
la.inv(A).dot(b)

array([1500.,  700.])