# Generating Data

In [1]:
import numpy as np

In [2]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.ones((2, 3)) * 10

array([[10., 10., 10.],
       [10., 10., 10.]])

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.random()

0.25392285649636326

In [12]:
np.random.random((2, 3))

array([[0.10323102, 0.4034437 , 0.95466889],
       [0.37987982, 0.55445382, 0.56201936]])

In [14]:
np.random.randn(2, 3) # Random numbers from normal distribuition (RandN[ormal])

array([[-0.13932626,  0.52038823,  0.80052385],
       [ 1.79610748, -1.85697335,  0.18384911]])

In [17]:
random_n = np.random.randn(10000)

random_n

array([ 0.06673158,  0.56735749,  0.74879009, ...,  0.6486688 ,
       -0.03513304,  0.01090761])

In [18]:
random_n.mean()

-0.008839715672624336

In [19]:
np.mean(random_n)

-0.008839715672624336

In [21]:
random_n.var()

1.0182610505739993

In [20]:
np.var(random_n)

1.0182610505739993

In [22]:
random_n.std()

1.0090892183419657

In [23]:
np.std(random_n)

1.0090892183419657

In [24]:
normal_n = np.random.randn(10000, 3)

normal_n.shape

(10000, 3)

In [25]:
normal_n.mean(axis=0) # For each column

array([ 0.00077524, -0.00287081,  0.00041948])

In [26]:
normal_n.mean(axis=1) # For each row

array([-0.04235057,  0.47621194, -0.14862213, ..., -0.29081749,
       -0.25375814,  0.31956117])

In [27]:
np.cov(normal_n)

array([[ 1.23065828,  0.34610486,  0.46213157, ...,  0.19731492,
        -0.46152274,  0.0361057 ],
       [ 0.34610486,  1.34972951,  0.0440464 , ..., -0.1244019 ,
        -0.55709671, -0.66912008],
       [ 0.46213157,  0.0440464 ,  0.1794324 , ...,  0.08643663,
        -0.14399378,  0.06016044],
       ...,
       [ 0.19731492, -0.1244019 ,  0.08643663, ...,  0.05747604,
        -0.01261979,  0.10336   ],
       [-0.46152274, -0.55709671, -0.14399378, ..., -0.01261979,
         0.31887   ,  0.2182192 ],
       [ 0.0361057 , -0.66912008,  0.06016044, ...,  0.10336   ,
         0.2182192 ,  0.36948496]])

In [28]:
np.cov(normal_n).shape

(10000, 10000)

In [29]:
np.cov(normal_n.T)

array([[ 0.98017813, -0.00515064,  0.01509965],
       [-0.00515064,  0.98250503, -0.0043809 ],
       [ 0.01509965, -0.0043809 ,  0.99393994]])

In [30]:
np.cov(normal_n, rowvar=False)

array([[ 0.98017813, -0.00515064,  0.01509965],
       [-0.00515064,  0.98250503, -0.0043809 ],
       [ 0.01509965, -0.0043809 ,  0.99393994]])

In [31]:
# numpy.random.randint(low, high=None, size=None, dtype='I')
np.random.randint(0, 10, size=(3, 3))

array([[6, 2, 2],
       [7, 1, 5],
       [5, 6, 1]])

In [32]:
# numpy.random.choice(array-like or int, size=None, replace=True, p=None)
np.random.choice(10, size=(3, 3))

array([[7, 4, 2],
       [3, 8, 8],
       [1, 3, 2]])